apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loader
  template:
    metadata:
      labels:
        app: code-nginx
    spec:
      containers:
      - name: code-nginx
        image: busybox
        ports:
        - containerPort: 80
